language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
install:
- cp -f $JAVA_HOME/jre/lib/security/cacerts target/travis-settings/cacerts
- chmod u+w target/travis-settings/cacerts
- "$JAVA_HOME/jre/bin/keytool -import -v -noprompt -storepass changeit -storetype
  jks -trustcacerts -alias IndigoBlueRoot -file target/travis-settings/ROOT-CA.crt
  -keystore target/travis-settings/cacerts"
script: mvn -Djavax.net.ssl.trustStore=$PWD/target/travis-settings/cacerts -B -V --settings
  target/travis-settings/settings.xml verify -U
after_success:
- '[[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]] || [[ $TRAVIS_TAG
  == release-* ]] && mvn -Djavax.net.ssl.trustStore=$PWD/target/travis-settings/cacerts
  -DskipTests=true -B -V --errors deploy --settings target/travis-settings/settings.xml'
env:
  global:
  - secure: BIg5suHNkdo7N4g9sduBHD3W+f6ADh88onaP19w7ZNTR+4TDGxXYToux11zAfH82KhWmC06ynDOC0qlLPNp/D0b07ScIa84C53VljXJuwKKxTibeEddkrFFgJNYyyTAQrjh8fYAqO1RfAgpXVbs1htGpHoGaFJ5UG1xxzKgWo1M5wtlHSjKDygGAHCaHEpmhqGNVZdRoj80dxoikUzOzSZc5nmFQzk1O/aZ0keGm02/MqR4EvA1Cmp5VmbX+8rdWY9aE5ctzCNlocfOM6HTAlfcEwkoIRZKfH8ak45MddZ55QZ5Diyu8F2lTQsbH2Rr8t0WdeFu1oDk7E+5S7J1c6FvpEDM3550+LMTNUIxrJDjJt/sOm/SYDEeTp5ZFzfdZLa98Ciga/oPp7GbUdnjaRM+Z5wNQ+tbYOZ36za+rxmcGZCw4GXpZKN46yAnmtmx3AnjTepVhpI8/EbqPpr8YHB2ndbfPFSVH7YK7VT3IvBFymDfNgnLrz3403fg7FAs0rAlFjHay8W6foK5yfm+feiqhZEvBhOzz6KmMFVB5ZawDLG8zrMjrhLg0heifKGtAkfCF1ygZFbJGq580hWVWQGxpSN3QW8vi5O4W5uMB6Ul+uB9nccdB/RlCWgyn4GT47E9JqAeksWtROcgM6TjTB74XyILaL7fJCRGSYJhoqqk=
  - secure: pvd1PfYZpZUTiA2oIPUIuaHBo/YMB83D9wgUhFNQcmRELIdtdykJnIpgbOlak0B1UZxK3rWR3tN+IMQ5g7xt8tVBEmGqA9ZQCwGtBatHDQuH7z8bdex+uzYrflxUXYs8KMop8rPfuYUuiHH415Nlx6cgT/x10NM2rnVRdNwBtFm1T+FCvS9oSoDuGRoHfhGT4YlpL9AGcRqs2kCTJomMN129wmLiFaH07CoZFvrdCHXnROIYp7KkVamzkbmuDw+NKyGTqD41HeayjHaebfbxReU2nhPV91E2SSoBusnJIXXWOrzhcKEHsLwlkaAt90pHXKDSfS6X1q/dek5RMrTu+uFzMlIGqxpM70Zy4jIHBAUVPB+PM7thNqwYKNwimeN3+Xwsy3hj3TriRNH9otZp/dbvlO8bV7adeXRWMiNNAQu4Pm5wOASpEMY1d9oChakBF8BD7Jvjp7FpKwnAk4pUPI9GTxj173/Aph43QIOvE+f/bCb8THmwCncWTyW7/pIh2RuWEoJDsmkqKGcJplF+f2y0WEyP+74ALwcMy2Bpu0Q0RJAWK5iWeQ2mux/5U2N5u3c6yJ0FiYb+NI7g9F69lP+fiminOJZ1TBb9nN1Wj/HXj9FEFnZs+otLZf8E8oYR6Ez6JDpvpLSr2L9sw+ZYjPDOATGRjQxxNkvWmnPwIAM=
