language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
install:
- cp -f $JAVA_HOME/jre/lib/security/cacerts target/travis-settings/cacerts
- chmod u+w target/travis-settings/cacerts
- "$JAVA_HOME/jre/bin/keytool -import -v -noprompt -storepass changeit -storetype
  jks -trustcacerts -alias IndigoBlueRoot -file target/travis-settings/ROOT-CA.crt
  -keystore target/travis-settings/cacerts"
script: mvn -Djavax.net.ssl.trustStore=$PWD/target/travis-settings/cacerts -B -V --settings
  target/travis-settings/settings.xml verify
after_success:
- '[[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]] || [[ $TRAVIS_TAG
  == release-* ]] && mvn -Djavax.net.ssl.trustStore=$PWD/target/travis-settings/cacerts
  -DskipTests=true -B -V --errors deploy --settings target/travis-settings/settings.xml'
env:
  global:
    secure: gpVTYhslb5Z3MEHZ2GG2cuylQk2G1mZw01K7zlflQrjijC0RAjawsyVxxQPf9JSXnvUurXNxg24OXefBe/OyYdW4Vy28U9s88m63ddB3BS15n/R0bzb5AcQ5tzvDYrP5nC56jDwWmwQ49h6uLR0gw0lbY1A7psrJutQvuwqtfKZMr5ZSZmoDmnhLNt3l2+nh52vgqv3q+yHXJj9la/thShvNu/10dy2dmzH9BXqKkIqcZeFwem3CN3lwziyL22iyIeCqucNlZc1dQ4Bsx+dR9IKiO2D/Xye8te0y2pbnQuf+6fbqBEyFucU0i8NTqV0rFquEQjAgXtjB/uKmNmICtb69Wk5Xlq2Zz00lNVzxOZxvJtjXs4BaBKou9IBXTuRWHKRLKbPDE1xA1W2EtUjiHYU8/7vXqlvCvnQcyfzP8FWsW1IDSb8EWR37uW2j3505lVkJnw8Z10czh9tBCklyzCntztqCkSVn04+Wm0DfbA8nFg3YUYDAZcJfTZLhcT8C5rQU0ibQbxwqunCtvW54oFqBfxjjFCBitsBy6TP1HWg1DcuR03PJe3SZ38iF9bBxrXGgWl7+VE45+QKtsbCXYcokmDs1Enj1f7PbfElZo9KO0Y173OR5i5tcD26ln+Epfhbb8tBgneI7skRecKO3SXDflVy8cRatWFRtemRgFIM=
